import type { KeypairType } from '@polkadot/util-crypto/types'

import * as Kilt from '@kiltprotocol/sdk-js'

import { Keyring } from '@polkadot/api'
import { config } from 'dotenv'
import { mnemonicGenerate } from '@polkadot/util-crypto'

import * as utils from './utils'

type EnvConfig = {
  wsAddress: string
  submitterAddress: Kilt.KiltAddress
  didMnemonic: string
  keyType: KeypairType
}

function parseEnv(): EnvConfig {
  config()
  let wsAddress = process.env.WS_ADDRESS
  if (!wsAddress) {
    const defaultWsAddress = utils.defaults.wsAddress
    console.log(
      `WS_ADDRESS not specified. Using '${defaultWsAddress}' by default.`
    )
    wsAddress = defaultWsAddress
  }

  const submitterAddress = process.env.SUBMITTER_ADDRESS as Kilt.KiltAddress
  if (!submitterAddress) {
    throw `No SUBMITTER_ADDRESS env variable specified.`
  }

  // If generated with Sporran, the Sporran mnemonic must be prefixed with `//did//0`.
  // E.g., advice carry faith comfort idle swift trim skill snow tornado lion dance//did//0
  // Otherwise, the one generated by this script can be used
  let didMnemonic = process.env.DID_MNEMONIC
  if (!didMnemonic) {
    console.log('DID_MNEMONIC not specified. Generating a random one...')
    didMnemonic = mnemonicGenerate()
    console.log(
      `DID mnemonic: ${didMnemonic}. Please save this somewhere safe.`
    )
  }

  let keyType = process.env.DID_KEY_TYPE as KeypairType
  if (!keyType) {
    const defaultKeyType = utils.defaults.keyType
    console.log(
      `DID_KEY_TYPE not specified. Using '${defaultKeyType}' by default.`
    )
    keyType = defaultKeyType
  }

  return { wsAddress, submitterAddress, didMnemonic, keyType }
}

async function main() {
  const { wsAddress, submitterAddress, didMnemonic, keyType } = parseEnv()

  const keyring = new Keyring()
  await Kilt.connect(wsAddress)

  const authKey = keyring.addFromMnemonic(
    didMnemonic,
    {},
    keyType
  ) as Kilt.KiltKeyringPair
  const fullDidCreationTx = await Kilt.Did.Chain.getStoreTx(
    {
      authentication: [authKey],
    },
    submitterAddress,
    utils.getKeypairSigningCallback(keyring)
  )

  const encodedOperation = fullDidCreationTx.toHex()
  console.log(
    `Encoded DID creation operation: ${encodedOperation}. Please submit this via PolkadotJS with the account provided here.`
  )
}

main()
  .catch((e) => console.error(e))
  .then(() => process.exit(0))
