import type { KeypairType } from '@polkadot/util-crypto/types'

import * as Kilt from '@kiltprotocol/sdk-js'

import { Keyring } from '@polkadot/api'
import { config } from 'dotenv'
import { mnemonicGenerate } from '@polkadot/util-crypto'

import * as utils from './utils'

type EnvConfig = {
  wsAddress: string
  submitterAddress: Kilt.KiltAddress
  didMnemonic: string
  keyType: KeypairType
  didUri?: Kilt.DidUri
  serviceId: Kilt.DidServiceEndpoint['id']
  serviceType: Kilt.DidServiceEndpoint['type'][number]
  serviceUrl: Kilt.DidServiceEndpoint['serviceEndpoint'][number]
}

function parseEnv(): EnvConfig {
  config()
  let wsAddress = process.env.WS_ADDRESS
  if (!wsAddress) {
    const defaultWsAddress = utils.defaults.wsAddress
    console.log(
      `WS_ADDRESS not specified. Using '${defaultWsAddress}' by default.`
    )
    wsAddress = defaultWsAddress
  }

  const submitterAddress = process.env.SUBMITTER_ADDRESS as Kilt.KiltAddress
  if (!submitterAddress) {
    throw `No SUBMITTER_ADDRESS env variable specified.`
  }

  // If generated with Sporran, the Sporran mnemonic must be prefixed with `//did//0`.
  // E.g., advice carry faith comfort idle swift trim skill snow tornado lion dance//did//0
  // Otherwise, the one generated by this script can be used
  let didMnemonic = process.env.DID_MNEMONIC
  if (!didMnemonic) {
    console.log('DID_MNEMONIC not specified. Generating a random one...')
    didMnemonic = mnemonicGenerate()
    console.log(
      `DID mnemonic: ${didMnemonic}. Please save this somewhere safe.`
    )
  }

  let keyType = process.env.DID_KEY_TYPE as KeypairType
  if (!keyType) {
    const defaultKeyType = utils.defaults.keyType
    console.log(
      `DID_KEY_TYPE not specified. Using '${defaultKeyType}' by default.`
    )
    keyType = defaultKeyType
  }

  const serviceId = process.env.SERVICE_ID as Kilt.DidServiceEndpoint['id']
  if (!serviceId) {
    throw `No SERVICE_ID env variable specified.`
  }

  const serviceType = process.env
    .SERVICE_TYPE as Kilt.DidServiceEndpoint['type'][number]
  if (!serviceType) {
    throw `No SERVICE_TYPE env variable specified.`
  }

  const serviceUrl = process.env
    .SERVICE_URL as Kilt.DidServiceEndpoint['serviceEndpoint'][number]
  if (!serviceUrl) {
    throw `No SERVICE_URL env variable specified.`
  }

  return {
    wsAddress,
    submitterAddress,
    didMnemonic,
    keyType,
    serviceId,
    serviceType,
    serviceUrl,
  }
}

async function main() {
  const {
    wsAddress,
    submitterAddress,
    didMnemonic,
    keyType,
    didUri: parsedDidUri,
    serviceId,
    serviceType,
    serviceUrl,
  } = parseEnv()

  const keyring = new Keyring()
  await Kilt.connect(wsAddress)

  // Re-create DID auth key
  const authKey = keyring.addFromMnemonic(
    didMnemonic,
    {},
    keyType
  ) as Kilt.KiltKeyringPair
  let didUri = parsedDidUri
  if (!didUri) {
    const defaultDidUri: Kilt.DidUri =
      Kilt.Did.Utils.getFullDidUriFromKey(authKey)
    console.log(
      `DID URI not specified. Using '${defaultDidUri}' as derived from the mnemonic by default.`
    )
    didUri = defaultDidUri
  }
  const fullDid: Kilt.DidDocument = {
    uri: didUri,
    authentication: [
      {
        ...authKey,
        // Not needed
        id: '#key',
      },
    ],
  }

  const addServiceTx = await Kilt.Did.Chain.getAddEndpointExtrinsic({
    id: serviceId,
    type: [serviceType],
    serviceEndpoint: [serviceUrl],
  })
  const authorizedAddServiceTx = await Kilt.Did.authorizeExtrinsic(
    fullDid,
    addServiceTx,
    utils.getKeypairSigningCallback(keyring),
    submitterAddress
  )

  const encodedOperation = authorizedAddServiceTx.toHex()
  console.log(
    `Encoded service endpoint addition operation: ${encodedOperation}. Please submit this via PolkadotJS with the account provided here.`
  )
}

main()
  .catch((e) => console.error(e))
  .then(() => process.exit(0))
